### ISSUE TITLE
cannot open display: :0

### ISSUE THREAD

**Issue by kakawait** [dadevel/docker-pulse-secure#1]
I'm trying to test your solution but I've following error

```
t:latest
usermod: no changes
pulseui.info pid of pulsesvc = 0 (pulseUi.cpp:153)
No protocol specified

(pulseUi:17): Gtk-WARNING **: 22:21:31.267: cannot open display: :0
``` 

As you can see `usermod: no changes` because I've removed `--env "GROUP_ID=$(id -g)"`  otherwise 

```
usermod: group '985' does not exist
``` 

I'm running docker using `sudo`

**Comment by dadevel** [comment]
What distro are you using?
Is SELinux or AppArmor enabled?
Are you using Wayland or X11?
If you are on X, try running `xhost +si:localuser:$USER` before starting the container.

**Comment by kakawait** [comment]
@dadevel thank for your time

> What distro are you using?

Archlinux

> Is SELinux or AppArmor enabled?

Nop

> Are you using Wayland or X11?

X11 (i3)

>  If you are on X, try running xhost +si:localuser:$USER before starting the container.

I'll try, in addition I think I may do something with `XAuthority`

I'll check deeper

**Comment by dadevel** [comment]
> I'll try, in addition I think I may do something with `XAuthority`

That's what I thought too. Did the `xhost` command help?

**Comment by kakawait** [comment]
> > I'll try, in addition I think I may do something with `XAuthority`
> 
> That's what I thought too. Did the `xhost` command help?

Not test yet. I don't have my linux laptop atm :)

**Comment by kakawait** [comment]
@dadevel with `xhost` that work :+1: 

Is safe enough? I didn't know that command. I'll check otherwise.
There is some command to undo what ` xhost` did, to cleanup after usage?

**Comment by dadevel** [comment]
I think it's safe. Whatever that's worth :smile:

What does the command do? It allows every user on your computer that has the same user id as the user given to the `xhost` command to access the xserver instance of the given user. In this case the given user is `$USER` aka "yourself". So you permit yourself to access your own xserver. This sounds strange but has the effect that a user inside a container that has the same user id can now talk to your xserver instance.

A better solution would involve `XAuthority` as you already mentioned. Mounting `~/.Xauthority` into the container should work, but didn't for me and I couldn't figure out why.

You can revert it with `xhost -si:localuser:$USER`.
